name: SCAD lab build

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: write
  packages: read

jobs:
  scad:
    uses: brainboxemb/tool.scad-project/.github/workflows/project-build.yml@v0.14.9
    with:
      artifact_name: hub75-component-lab-build
      publish: true
